#############################
##
## Created by Jaemin Shin
##
## Modified 20151104 by Savannah Cookson
## Handled single contrast exception logic in rendering command; previously
## did not format layout properly if only one set of contrast symbols
## and labels was included in input. Backslashes were misplaced.
##
## Formatted and Documented by Savannah Cookson 20150629
## Encapsulation by Savannah Cookson 20150723
##
## The following script runs the afni_proc.py function of AFNI
## for each subject indicated in the for loop to generate the
## analysis script for each sub. This script is called by the
## processing_shell.sh script.
##
## WARNING: DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING!
##
#############################

rm temp.sh

############
## Organize user inputs and format for insertion
############
subject="$1"
studySuffix="$2"
blocks="$3"
acqSeq="$4"
blur="$5"
stimLabels="$6"
shift 6
contrasts=("${@}")

subjID=$subject'_'$studySuffix

############
## Intelligently identifies the contrast expressions and labels and total number of contrasts.
############
errorCatch=false
if [ $[${#contrasts[@]}%2] -eq 0 ];
then
	contrastScript=$''
	declare -i i
	i=0
	while [ $i -le $[$[${#contrasts[@]}/2]-1] ]
	do
		expression="${contrasts[$[$[i*2]]]}"
		label=${contrasts[$[i*2]+1]}

		contrastScript="$contrastScript"$'\n-gltsym '"'"'SYM: '"$expression""'"' \'$'\n-glt_label '$[i+1]' '$label' \'
	

		let 'i += 1'

	done

	addtlCons=''
	if [ $i -gt 10 ];
	then
		addtlCons=' \'$'\n-num_glt '$i' \'
	fi
else
	echo 'incorrect number of items entered for one or more contrasts'
	errorCatch=true
fi

############
## The following portion of the script formats and then runs the afni_proc.py command.
############
if $errorCatch;
	then
	echo 'script failed; check your contrasts.'
else 

echo -e 'afni_proc.py \
-subj_id '$subjID' \
-copy_anat '$subject'/anat/orig/T1.nii \
-dsets '$subject'/func/orig/fMRI_run*.nii \
-blocks '$blocks' regress \
-tshift_opts_ts -tpattern '$acqSeq' \
-script '$subjID'.tcsh \
-volreg_align_to third \
-volreg_align_e2a \
-align_opts_aea -AddEdge \
-volreg_tlrc_warp \
-tlrc_base MNI_avg152T1+tlrc \
-regress_censor_motion 0.2 -regress_censor_outliers 0.1 \
-blur_size '$blur' \
-regress_stim_times '$subject'/stim/*.1D \
-regress_stim_types AM2 \
-regress_stim_labels '"$stimLabels"' \
-regress_basis ''dmBLOCK'' \
-regress_local_times \
-regress_opts_3dD \'"$addtlCons""$contrastScript"'
-float \
-jobs 4 \
-regress_est_blur_epits \
-regress_est_blur_errts \
-regress_run_clustsim no \
-bash' > temp.sh

sh temp.sh
rm temp.sh

fi
