###############
##
## Created by Jaemin Shin
##
## Documented by Savannah Cookson 20150629
## Encapsulation by Savannah Cookson 20150723
##
## Modified by Savannah Cookson 20160719
## Adapted script to handle subject IDs that start with numbers
##
## Modified by Savannah Cookson 20160120
## Fixed parallel-proc.sh call to tcsh-shell.sh
##
## Modified by Savannah Cookson 20150910
## Script now points to sync folder
##
## The following shell script calls each of your individual subject analysis
## scripts created by afni_proc.py (see "3_example_afni_proc_script.sh") using
## the tcsh_shell (see "4_tcsh_shell.sh") and submits them to the parallel
## CABI processing units.
##
## DO NOT EDIT THIS FILE IF YOU DO NOT KNOW WHAT YOU ARE DOING!
##
###############

subject=$1
studySuffix=$2
analysisdirectory=$3
scriptsdir=$4

subjID=$subject'_'$studySuffix
echo $subjID
jobID=job_$subjID

############
## Indicate the name of the folder containing the data for each  
## subject. This value must exactly match each folder name.
############

echo 'Parallelizing' # prints the current subject number for progress logging.
# Make a log folder if one doesn't already exist
mkdir -p ${analysisdirectory}/log

# Call the program qsub for parallel computing on the CABI clusters.
# Though not necessary, the name of the log files may be changed.
qsub \
-e ${analysisdirectory}/log/analysis.${subject}.output.log \
-o ${analysisdirectory}/log/analysis.${subject}.output.log \
-N $jobID \
-S /bin/sh \
$scriptsdir/tcsh_shell.sh ${subjID} $analysisdirectory
